[project]
name = "mcp-servers"
version = "0.1.0"
description = "MCP servers"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.12.0",
    "requests>=2.31.0",
    "soundfile",
    "sounddevice",
    "kokoro-onnx",
    "fastmcp>=2.12.2",
]
